language: ruby
cache: bundler
rvm:
  - 2.2.2
services:
  - postgresql
addons:
  postgresql: "9.3"
script:
  - "bundle exec spring rspec spec"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "bundle exec rake db:create"
  - "bundle exec rake db:migrate"
  - "bundle exec rake bower:install"
sudo: true
dist: trusty
